com.devdaily.sarah.tests.TrySuccessFailure$AlsException: Bummer!
    at com.devdaily.sarah.tests.TrySuccessFailure$$anonfun$badAdder$1.apply$mcI$sp(TrySuccessFailure.scala:31)
    at com.devdaily.sarah.tests.TrySuccessFailure$$anonfun$badAdder$1.apply(TrySuccessFailure.scala:27)
    at com.devdaily.sarah.tests.TrySuccessFailure$$anonfun$badAdder$1.apply(TrySuccessFailure.scala:27)
    at scala.util.Try$.apply(Try.scala:161)
    at com.devdaily.sarah.tests.TrySuccessFailure$.badAdder(TrySuccessFailure.scala:27)
    at com.devdaily.sarah.tests.TrySuccessFailure$delayedInit$body.apply(TrySuccessFailure.scala:8)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at com.devdaily.sarah.tests.TrySuccessFailure$.main(TrySuccessFailure.scala:6)
    at com.devdaily.sarah.tests.TrySuccessFailure.main(TrySuccessFailure.scala)

Caused by: java.io.IOException: Boom!
    at com.devdaily.sarah.tests.TrySuccessFailure$$anonfun$badAdder$1.apply$mcI$sp(TrySuccessFailure.sccom.devdaily.sarah.tests.TrySuccessFailure$AlsException: Bummer!
    at com.devdaily.sarah.tests.TrySuccessFailure$$anonfun$badAdder$1.apply$mcI$sp(TrySuccessFailure.scala:31)
    at com.devdaily.sarah.tests.TrySuccessFailure$$anonfun$badAdder$1.apply(TrySuccessFailure.scala:27)
    at com.devdaily.sarah.tests.TrySuccessFailure$$anonfun$badAdder$1.apply(TrySuccessFailure.scala:27)
    at scala.util.Try$.apply(Try.scala:161)
    at com.devdaily.sarah.tests.TrySuccessFailure$.badAdder(TrySuccessFailure.scala:27)
    at com.devdaily.sarah.tests.TrySuccessFailure$delayedInit$body.apply(TrySuccessFailure.scala:8)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at com.devdaily.sarah.tests.TrySuccessFailure$.main(TrySuccessFailure.scala:6)
    at com.devdaily.sarah.tests.TrySuccessFailure.main(TrySuccessFailure.scala)

Caused by: java.io.IOException: Boom!
    at com.devdaily.sarah.tests.TrySuccessFailure$$anonfun$badAdder$1.apply$mcI$sp(TrySuccessFailure.scala:30)
